# Generated by Django 4.2.1 on 2023-05-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0003_alter_transacao_data_alter_transacao_observacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transacoes'},
        ),
    ]
